/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_novip_novip_Native */

#ifndef _Included_com_novip_novip_Native
#define _Included_com_novip_novip_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_novip_novip_Native
 * Method:    verifyVip
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_novip_novip_Native_verifyVip
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
